version: '3.7'
services:
    mssql:
        image: chriseaton/adventureworks:latest
        restart: always
        environment:
          SA_PASSWORD: 'MSSQLServer@2019'
          ACCEPT_EULA: 'Y'
        ports:
          - '1433:1433'
        volumes:
          - ./my-db:/var/lib/mysql
    iris:
      build: 
        context: .
        dockerfile: Dockerfile
      restart: always
      ports: 
        - 1972:1972
        - 52773:52773
        - 53773:53773
      volumes:
        - ./:/irisrun/repo