version: '3.7'
services:
    mssql:
        image: chriseaton/adventureworks:latest
        restart: always
        environment:
          - MSSQL_SA_PASSWORD: 'MSSQLServer@2019'
          - ACCEPT_EULA: 'Y'
        ports:
          - '1433:1433'
        volumes:
          - ./mssql:/var/lib/mssql
    iris:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      environment:
        - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
      ports:
        - 1972:1972
        - 52773
        - 53773
      volumes:
        - ./:/home/irisowner/dev
